# appspec.yml - CodeDeploy configuration
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 30
      runas: root