branch-defaults:
  main:
    environment: NodeApp-env
    group_suffix: null
global:
  application_name: NodeApp
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: Node.js
  platform_version: 18
  workspace_type: Application

# Create Elastic Beanstalk environment
Resources:
  NodeAppEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref "NodeApp"
      SolutionStackName: "64bit Amazon Linux 2023 v6.0.1 running Node.js 18"
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: aws-elasticbeanstalk-ec2-role
        - Namespace: aws:elasticbeanstalk:environment
          OptionName: EnvironmentType
          Value: LoadBalanced
